### ISSUE TITLE
Is anybody still maintaining milkman?

### ISSUE THREAD

**Issue by jsaz** [ccollins/milkman#32]
There are a few people interested in this project. However, the last commit was almost 8 months ago. The last publish on PyPI was over a year ago. Currently, `pip install milkman` is broken (see Issues #30 and #31).

I really want to use milkman, and not one of the alternatives (factoryboy, ModelMommy, straight-up Django fixtures, etc.). I'm tempted to fork it and start pushing updates to PyPI, but I don't want to step on anybody's toes.

So...is anybody still maintaining milkman?

**Comment by klen** [comment]
That the reason why I've build [mixer](https://github.com/klen/mixer).

**Comment by jsaz** [comment]
After forking this myself, I found a drop-in replacement that seems fairly well-maintained. Checkout https://pypi.python.org/pypi/django-dynamic-fixture/1.8.1 and some Django example usage at http://codeinthehole.com/writing/prefer-webtest-to-djangos-test-client-for-functional-tests/.

So long, milkman, and thanks for all the mock data!
