### ISSUE TITLE
Milkman doesn't actually deliver a model that is inherited from another model

### ISSUE THREAD

**Issue by sethtrain** [ccollins/milkman#4]
Well, kinda.  An instance of the model is delivered but all the fields that are inherited aren't filled in.  I plan to start working on a solution but thought I would make an issue for your record.

**Comment by ccollins** [comment]
Word.

If you can submit a failing test that would be awesome.  If not, I'll try to take a look at it soon.

**Comment by sethtrain** [comment]
Closing.  Fixed with: 31f9af9cc539e15b6e57
