### ISSUE TITLE
The example on pypi is invalid

### ISSUE THREAD

**Issue by daks** [ccollins/milkman#7]
Hi,

On Pypi http://pypi.python.org/pypi/milkman/0.4.3 in the example use of milkman, it's written:
    from milkman import milkman. 
This doesn't work, could you sync the information given on pypi with the one written here on github, or simply link to here.

thanks

**Comment by danostrowski** [comment]
Where is this controlled? I guess it's not pulled from a README or anything convenient....

**Comment by sethtrain** [comment]
You can see an example of the correct usage here: https://github.com/ccollins/milkman/blob/master/testapp/tests.py

Although this should be fixed and updated on pypi.

**Comment by ccollins** [comment]
Updating pypi.
